require(doParallel)
require(parallel)
require(fclust)
require(clue)
source("kspline.R")
source("randgenuc.R")
source("loss_function.R")
source("FERFRKM.R")
source("CV_FERFRKM.R")
source("init_FERFRKM.R")
source("make_folds.R")
source("rand_orthogonal.R")
source("preggq_int.R")
# load model selection
load("data/modelsel_plane.RData")
