require(doParallel)
require(parallel)
require(fclust)
require(clue)
source("functions/kspline.R")
source("functions/randgenuc.R")
source("functions/loss_function.R")
source("functions/FERFRKM.R")
source("functions/CV_FERFRKM.R")
source("functions/init_FERFRKM.R")
source("functions/make_folds.R")
source("functions/rand_orthogonal.R")
source("functions/preggq_int.R")
# load model selection
load("data/modelsel_plane.RData")